## Generated SDC file "eth4to1.out.sdc"

## Copyright (C) 2017  Intel Corporation. All rights reserved.
## Your use of Intel Corporation's design tools, logic functions 
## and other software and tools, and its AMPP partner logic 
## functions, and any output files from any of the foregoing 
## (including device programming or simulation files), and any 
## associated documentation or information are expressly subject 
## to the terms and conditions of the Intel Program License 
## Subscription Agreement, the Intel Quartus Prime License Agreement,
## the Intel MegaCore Function License Agreement, or other 
## applicable license agreement, including, without limitation, 
## that your use is for the sole purpose of programming logic 
## devices manufactured by Intel and sold by Intel or its 
## authorized distributors.  Please refer to the applicable 
## agreement for further details.


## VENDOR  "Altera"
## PROGRAM "Quartus Prime"
## VERSION "Version 16.1.2 Build 203 01/18/2017 SJ Standard Edition"

## DATE    "Sun Dec 10 18:04:23 2017"

##
## DEVICE  "5SGXEA7N2F45C2"
##


#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3



#**************************************************************
# Create Clock
#**************************************************************

create_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} -period 0.193 -waveform { 0.000 0.096 } [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}]
create_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} -period 0.193 -waveform { 0.000 0.096 } [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}]
create_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} -period 0.193 -waveform { 0.000 0.096 } [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}]
create_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} -period 0.193 -waveform { 0.000 0.096 } [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}]
create_clock -name {SFP_REFCLK_p} -period 1.551 -waveform { 0.000 0.775 } [get_ports {SFP_REFCLK_p}]
create_clock -name {OSC_50_B3B} -period 20.000 -waveform { 0.000 10.000 } [get_ports { OSC_50_B3B }]


#**************************************************************
# Create Generated Clock
#**************************************************************

create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 10 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 20 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|refclk}] -duty_cycle 50/1 -multiply_by 8 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.pll_mux.pll_refclk_select_mux|clkout} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.pll_mux.pll_refclk_select_mux|clkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.pll_mux.pll_refclk_select_mux|refiqclk9}] -duty_cycle 50/1 -multiply_by 1 -master_clock {SFP_REFCLK_p} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.pll_mux.pll_refclk_select_mux|clkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 10 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 20 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1b}] -duty_cycle 50/1 -multiply_by 1 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 10 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 20 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|refclk}] -duty_cycle 50/1 -multiply_by 8 -master_clock {SFP_REFCLK_p} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|cpulse}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|hfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 5 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|lfclkp}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 10 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[0]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 20 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|clkcdr1t}] -duty_cycle 50/1 -multiply_by 1 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|altera_pll_5G|pll[0].pll.cmu_pll.tx_pll|clkcdr} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[2]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|refiqclk0}] -duty_cycle 50/1 -multiply_by 1 -master_clock {SFP_REFCLK_p} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|refiqclk0}] -duty_cycle 50/1 -multiply_by 1 -master_clock {SFP_REFCLK_p} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|refiqclk9}] -duty_cycle 50/1 -multiply_by 1 -master_clock {SFP_REFCLK_p} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|refiqclk9}] -duty_cycle 50/1 -multiply_by 1 -master_clock {SFP_REFCLK_p} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.cdr_clkmux_nopcie.cdr_refclk_mux0|clkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}] -duty_cycle 50/1 -multiply_by 2 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] -duty_cycle 50/1 -multiply_by 40 -divide_by 66 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}] -duty_cycle 50/1 -multiply_by 2 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] -duty_cycle 50/1 -multiply_by 40 -divide_by 66 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}] -duty_cycle 50/1 -multiply_by 2 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] -duty_cycle 50/1 -multiply_by 40 -divide_by 66 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_rx_pcs|wys|rxclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes}] -duty_cycle 50/1 -multiply_by 2 -divide_by 40 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_cdr|clk90bdes} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b}] -duty_cycle 50/1 -multiply_by 40 -divide_by 66 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk90b} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|rx_pma.sv_rx_pma_inst|rx_pmas[0].rx_pma.rx_pma_deser|clk33pcs}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[3].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[2].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[1].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txpmaclk}] -duty_cycle 50/1 -multiply_by 1 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pma|tx_pma.sv_tx_pma_inst|tx_pma_insts[0].sv_tx_pma_ch_inst|tx_pma_ch.tx_cgb|pclk[1]} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|native_inst|inst_sv_pcs|ch[0].inst_sv_pcs_ch|inst_sv_hssi_10g_tx_pcs|wys|txclkout}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|g_fpll.altera_pll_156M~FRACTIONAL_PLL|vcoph[0]} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|g_fpll.altera_pll_156M~FRACTIONAL_PLL|refclkin}] -duty_cycle 50/1 -multiply_by 32 -divide_by 66 -master_clock {SFP_REFCLK_p} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|g_fpll.altera_pll_156M~FRACTIONAL_PLL|vcoph[0]}] 
create_generated_clock -name {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|g_fpll.altera_pll_156M~PLL_OUTPUT_COUNTER|divclk} -source [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|g_fpll.altera_pll_156M~PLL_OUTPUT_COUNTER|vco1ph[0]}] -duty_cycle 50/1 -multiply_by 1 -divide_by 2 -master_clock {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|g_fpll.altera_pll_156M~FRACTIONAL_PLL|vcoph[0]} [get_pins {mac10g_inst|mac10g_inst|xv_xcvr_10gbaser_nr_inst|ch[0].sv_xcvr_10gbaser_native_inst|g_fpll.altera_pll_156M~PLL_OUTPUT_COUNTER|divclk}] 


#**************************************************************
# Set Clock Latency
#**************************************************************



#**************************************************************
# Set Clock Uncertainty
#**************************************************************

set_clock_uncertainty -rise_from [get_clocks {OSC_50_B3B}] -rise_to [get_clocks {OSC_50_B3B}] -setup 0.070  
set_clock_uncertainty -rise_from [get_clocks {OSC_50_B3B}] -rise_to [get_clocks {OSC_50_B3B}] -hold 0.060  
set_clock_uncertainty -rise_from [get_clocks {OSC_50_B3B}] -fall_to [get_clocks {OSC_50_B3B}] -setup 0.070  
set_clock_uncertainty -rise_from [get_clocks {OSC_50_B3B}] -fall_to [get_clocks {OSC_50_B3B}] -hold 0.060  
set_clock_uncertainty -fall_from [get_clocks {OSC_50_B3B}] -rise_to [get_clocks {OSC_50_B3B}] -setup 0.070  
set_clock_uncertainty -fall_from [get_clocks {OSC_50_B3B}] -rise_to [get_clocks {OSC_50_B3B}] -hold 0.060  
set_clock_uncertainty -fall_from [get_clocks {OSC_50_B3B}] -fall_to [get_clocks {OSC_50_B3B}] -setup 0.070  
set_clock_uncertainty -fall_from [get_clocks {OSC_50_B3B}] -fall_to [get_clocks {OSC_50_B3B}] -hold 0.060  
set_clock_uncertainty -rise_from [get_clocks {SFP_REFCLK_p}] -rise_to [get_clocks {SFP_REFCLK_p}] -setup 0.030  
set_clock_uncertainty -rise_from [get_clocks {SFP_REFCLK_p}] -fall_to [get_clocks {SFP_REFCLK_p}] -setup 0.030  
set_clock_uncertainty -fall_from [get_clocks {SFP_REFCLK_p}] -rise_to [get_clocks {SFP_REFCLK_p}] -setup 0.030  
set_clock_uncertainty -fall_from [get_clocks {SFP_REFCLK_p}] -fall_to [get_clocks {SFP_REFCLK_p}] -setup 0.030  


#**************************************************************
# Set Input Delay
#**************************************************************



#**************************************************************
# Set Output Delay
#**************************************************************



#**************************************************************
# Set Clock Groups
#**************************************************************



#**************************************************************
# Set False Path
#**************************************************************

set_false_path -to [get_registers {*alt_xcvr_resync*sync_r[0]}]


#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************

set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] 20.000
set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] 20.000
set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] 20.000
set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] 20.000
set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] 20.000
set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] 20.000
set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] 20.000
set_max_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] 20.000
set_max_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] 20.000


#**************************************************************
# Set Minimum Delay
#**************************************************************

set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] -10.000
set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] -10.000
set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] -10.000
set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] -10.000
set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_rx_pld_pcs_interface_rbc:inst_sv_hssi_rx_pld_pcs_interface|asynchdatain }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[2].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_common_pld_pcs_interface_rbc:inst_sv_hssi_common_pld_pcs_interface|pldnfrzdrv }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] -10.000
set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[3].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] -10.000
set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[1].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldlccmurstbout }] -10.000
set_min_delay -from [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|pldtxiqclkout }] -10.000
set_min_delay -to [get_ports { mac10g:mac10g_inst|altera_xcvr_10gbaser:mac10g_inst|sv_xcvr_10gbaser_nr:xv_xcvr_10gbaser_nr_inst|sv_xcvr_10gbaser_native:ch[0].sv_xcvr_10gbaser_native_inst|sv_xcvr_native:native_inst|sv_pcs:inst_sv_pcs|sv_pcs_ch:ch[0].inst_sv_pcs_ch|sv_hssi_tx_pld_pcs_interface_rbc:inst_sv_hssi_tx_pld_pcs_interface|asynchdatain }] -10.000


#**************************************************************
# Set Input Transition
#**************************************************************

