# TCL File Generated by Component Editor 16.1
# Mon May 07 18:35:42 EDT 2018
# DO NOT MODIFY


# 
# eth_packetstorage "Ethernet Packet Storage" v1.0
#  2018.05.07.18:35:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module eth_packetstorage
# 
set_module_property DESCRIPTION ""
set_module_property NAME eth_packetstorage
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Ethernet Packet Storage"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL packetstorage
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file packetstorage.sv SYSTEM_VERILOG PATH packetstorage.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL packetstorage
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file packetstorage.sv SYSTEM_VERILOG PATH packetstorage.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point outstream
# 
add_interface outstream avalon_streaming start
set_interface_property outstream associatedClock clock
set_interface_property outstream associatedReset reset
set_interface_property outstream dataBitsPerSymbol 8
set_interface_property outstream errorDescriptor ""
set_interface_property outstream firstSymbolInHighOrderBits true
set_interface_property outstream maxChannel 63
set_interface_property outstream readyLatency 0
set_interface_property outstream ENABLED true
set_interface_property outstream EXPORT_OF ""
set_interface_property outstream PORT_NAME_MAP ""
set_interface_property outstream CMSIS_SVD_VARIABLES ""
set_interface_property outstream SVD_ADDRESS_GROUP ""

add_interface_port outstream outstream_data data Output 64
add_interface_port outstream outstream_ready ready Input 1
add_interface_port outstream outstream_valid valid Output 1
add_interface_port outstream outstream_eop endofpacket Output 1
add_interface_port outstream outstream_sop startofpacket Output 1
add_interface_port outstream outstream_channel channel Output 6


# 
# connection point sendstream
# 
add_interface sendstream avalon_streaming start
set_interface_property sendstream associatedClock clock
set_interface_property sendstream associatedReset reset
set_interface_property sendstream dataBitsPerSymbol 8
set_interface_property sendstream errorDescriptor ""
set_interface_property sendstream firstSymbolInHighOrderBits true
set_interface_property sendstream maxChannel 3
set_interface_property sendstream readyLatency 0
set_interface_property sendstream ENABLED true
set_interface_property sendstream EXPORT_OF ""
set_interface_property sendstream PORT_NAME_MAP ""
set_interface_property sendstream CMSIS_SVD_VARIABLES ""
set_interface_property sendstream SVD_ADDRESS_GROUP ""

add_interface_port sendstream sendstream_data data Output 64
add_interface_port sendstream sendstream_valid valid Output 1
add_interface_port sendstream sendstream_ready ready Input 1
add_interface_port sendstream sendstream_eop endofpacket Output 1
add_interface_port sendstream sendstream_sop startofpacket Output 1
add_interface_port sendstream sendstream_channel channel Output 6


# 
# connection point tagstream
# 
add_interface tagstream avalon_streaming end
set_interface_property tagstream associatedClock clock
set_interface_property tagstream associatedReset reset
set_interface_property tagstream dataBitsPerSymbol 8
set_interface_property tagstream errorDescriptor ""
set_interface_property tagstream firstSymbolInHighOrderBits true
set_interface_property tagstream maxChannel 0
set_interface_property tagstream readyLatency 0
set_interface_property tagstream ENABLED true
set_interface_property tagstream EXPORT_OF ""
set_interface_property tagstream PORT_NAME_MAP ""
set_interface_property tagstream CMSIS_SVD_VARIABLES ""
set_interface_property tagstream SVD_ADDRESS_GROUP ""

add_interface_port tagstream tagstream_data data Input 8
add_interface_port tagstream tagstream_ready ready Output 1
add_interface_port tagstream tagstream_valid valid Input 1


# 
# connection point instream
# 
add_interface instream avalon_streaming end
set_interface_property instream associatedClock clock
set_interface_property instream associatedReset reset
set_interface_property instream dataBitsPerSymbol 8
set_interface_property instream errorDescriptor ""
set_interface_property instream firstSymbolInHighOrderBits true
set_interface_property instream maxChannel 0
set_interface_property instream readyLatency 0
set_interface_property instream ENABLED true
set_interface_property instream EXPORT_OF ""
set_interface_property instream PORT_NAME_MAP ""
set_interface_property instream CMSIS_SVD_VARIABLES ""
set_interface_property instream SVD_ADDRESS_GROUP ""

add_interface_port instream instream_data data Input 64
add_interface_port instream instream_eop endofpacket Input 1
add_interface_port instream instream_sop startofpacket Input 1
add_interface_port instream instream_ready ready Output 1
add_interface_port instream instream_valid valid Input 1

