# TCL File Generated by Component Editor 16.1
# Tue May 22 12:47:51 EDT 2018
# DO NOT MODIFY


# 
# ethpack2 "Ethernet Packet Storage 2" v1.0
#  2018.05.22.12:47:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ethpack2
# 
set_module_property DESCRIPTION ""
set_module_property NAME ethpack2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "G. Elliott"
set_module_property DISPLAY_NAME "Ethernet Packet Storage 2"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pmem_group_wrap
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pmem_group.sv SYSTEM_VERILOG PATH pmem_group.sv 
add_fileset_file pmem_group_wrap.sv SYSTEM_VERILOG PATH pmem_group_wrap.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pmem_group_wrap
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pmem_group.sv SYSTEM_VERILOG PATH pmem_group.sv
add_fileset_file pmem_group_wrap.sv SYSTEM_VERILOG PATH pmem_group_wrap.sv


# 
# parameters
# 


# 
# display items
# 

# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1



# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point packetin0
# 
add_interface packetin0 avalon_streaming end
set_interface_property packetin0 associatedClock clock
set_interface_property packetin0 associatedReset reset
set_interface_property packetin0 dataBitsPerSymbol 8
set_interface_property packetin0 symbolsPerBeat 8
set_interface_property packetin0 errorDescriptor ""
set_interface_property packetin0 firstSymbolInHighOrderBits true
set_interface_property packetin0 maxChannel 0
set_interface_property packetin0 readyLatency 0
set_interface_property packetin0 ENABLED true
set_interface_property packetin0 EXPORT_OF ""
set_interface_property packetin0 PORT_NAME_MAP ""
set_interface_property packetin0 CMSIS_SVD_VARIABLES ""
set_interface_property packetin0 SVD_ADDRESS_GROUP ""

add_interface_port packetin0 packetin_0_data data Input 64
add_interface_port packetin0 packetin_0_sop startofpacket Input 1
add_interface_port packetin0 packetin_0_eop endofpacket Input 1
add_interface_port packetin0 packetin_0_valid valid Input 1
add_interface_port packetin0 packetin_0_ready ready Output 1
# 
# connection point packetin1
# 
add_interface packetin1 avalon_streaming end
set_interface_property packetin1 associatedClock clock
set_interface_property packetin1 associatedReset reset
set_interface_property packetin1 dataBitsPerSymbol 8
set_interface_property packetin1 symbolsPerBeat 8
set_interface_property packetin1 errorDescriptor ""
set_interface_property packetin1 firstSymbolInHighOrderBits true
set_interface_property packetin1 maxChannel 0
set_interface_property packetin1 readyLatency 0
set_interface_property packetin1 ENABLED true
set_interface_property packetin1 EXPORT_OF ""
set_interface_property packetin1 PORT_NAME_MAP ""
set_interface_property packetin1 CMSIS_SVD_VARIABLES ""
set_interface_property packetin1 SVD_ADDRESS_GROUP ""

add_interface_port packetin1 packetin_1_data data Input 64
add_interface_port packetin1 packetin_1_sop startofpacket Input 1
add_interface_port packetin1 packetin_1_eop endofpacket Input 1
add_interface_port packetin1 packetin_1_valid valid Input 1
add_interface_port packetin1 packetin_1_ready ready Output 1

# 
# connection point packetin2
# 
add_interface packetin2 avalon_streaming end
set_interface_property packetin2 associatedClock clock
set_interface_property packetin2 associatedReset reset
set_interface_property packetin2 dataBitsPerSymbol 8
set_interface_property packetin2 symbolsPerBeat 8
set_interface_property packetin2 errorDescriptor ""
set_interface_property packetin2 firstSymbolInHighOrderBits true
set_interface_property packetin2 maxChannel 0
set_interface_property packetin2 readyLatency 0
set_interface_property packetin2 ENABLED true
set_interface_property packetin2 EXPORT_OF ""
set_interface_property packetin2 PORT_NAME_MAP ""
set_interface_property packetin2 CMSIS_SVD_VARIABLES ""
set_interface_property packetin2 SVD_ADDRESS_GROUP ""

add_interface_port packetin2 packetin_2_data data Input 64
add_interface_port packetin2 packetin_2_sop startofpacket Input 1
add_interface_port packetin2 packetin_2_eop endofpacket Input 1
add_interface_port packetin2 packetin_2_valid valid Input 1
add_interface_port packetin2 packetin_2_ready ready Output 1

# 
# connection point packetin3
# 
add_interface packetin3 avalon_streaming end
set_interface_property packetin3 associatedClock clock
set_interface_property packetin3 associatedReset reset
set_interface_property packetin3 dataBitsPerSymbol 8
set_interface_property packetin3 symbolsPerBeat 8
set_interface_property packetin3 errorDescriptor ""
set_interface_property packetin3 firstSymbolInHighOrderBits true
set_interface_property packetin3 maxChannel 0
set_interface_property packetin3 readyLatency 0
set_interface_property packetin3 ENABLED true
set_interface_property packetin3 EXPORT_OF ""
set_interface_property packetin3 PORT_NAME_MAP ""
set_interface_property packetin3 CMSIS_SVD_VARIABLES ""
set_interface_property packetin3 SVD_ADDRESS_GROUP ""

add_interface_port packetin3 packetin_3_data data Input 64
add_interface_port packetin3 packetin_3_sop startofpacket Input 1
add_interface_port packetin3 packetin_3_eop endofpacket Input 1
add_interface_port packetin3 packetin_3_valid valid Input 1
add_interface_port packetin3 packetin_3_ready ready Output 1



# 
# connection point packetout0
# 
add_interface packetout0 avalon_streaming start
set_interface_property packetout0 associatedClock clock
set_interface_property packetout0 associatedReset reset
set_interface_property packetout0 dataBitsPerSymbol 8
set_interface_property packetout0 symbolsPerBeat 8
set_interface_property packetout0 errorDescriptor ""
set_interface_property packetout0 firstSymbolInHighOrderBits true
set_interface_property packetout0 maxChannel 63
set_interface_property packetout0 readyLatency 0
set_interface_property packetout0 ENABLED true
set_interface_property packetout0 EXPORT_OF ""
set_interface_property packetout0 PORT_NAME_MAP ""
set_interface_property packetout0 CMSIS_SVD_VARIABLES ""
set_interface_property packetout0 SVD_ADDRESS_GROUP ""

add_interface_port packetout0 packetout_0_sop startofpacket Output 1
add_interface_port packetout0 packetout_0_eop endofpacket Output 1
add_interface_port packetout0 packetout_0_data data Output 64
add_interface_port packetout0 packetout_0_channel channel Output 6
add_interface_port packetout0 packetout_0_valid valid Output 1
add_interface_port packetout0 packetout_0_ready ready Input 1


# 
# connection point packetout1
# 
add_interface packetout1 avalon_streaming start
set_interface_property packetout1 associatedClock clock
set_interface_property packetout1 associatedReset reset
set_interface_property packetout1 dataBitsPerSymbol 8
set_interface_property packetout1 symbolsPerBeat 8
set_interface_property packetout1 errorDescriptor ""
set_interface_property packetout1 firstSymbolInHighOrderBits true
set_interface_property packetout1 maxChannel 63
set_interface_property packetout1 readyLatency 0
set_interface_property packetout1 ENABLED true
set_interface_property packetout1 EXPORT_OF ""
set_interface_property packetout1 PORT_NAME_MAP ""
set_interface_property packetout1 CMSIS_SVD_VARIABLES ""
set_interface_property packetout1 SVD_ADDRESS_GROUP ""

add_interface_port packetout1 packetout_1_sop startofpacket Output 1
add_interface_port packetout1 packetout_1_eop endofpacket Output 1
add_interface_port packetout1 packetout_1_data data Output 64
add_interface_port packetout1 packetout_1_channel channel Output 6
add_interface_port packetout1 packetout_1_valid valid Output 1
add_interface_port packetout1 packetout_1_ready ready Input 1


# 
# connection point packetout2
# 
add_interface packetout2 avalon_streaming start
set_interface_property packetout2 associatedClock clock
set_interface_property packetout2 associatedReset reset
set_interface_property packetout2 dataBitsPerSymbol 8
set_interface_property packetout2 symbolsPerBeat 8
set_interface_property packetout2 errorDescriptor ""
set_interface_property packetout2 firstSymbolInHighOrderBits true
set_interface_property packetout2 maxChannel 63
set_interface_property packetout2 readyLatency 0
set_interface_property packetout2 ENABLED true
set_interface_property packetout2 EXPORT_OF ""
set_interface_property packetout2 PORT_NAME_MAP ""
set_interface_property packetout2 CMSIS_SVD_VARIABLES ""
set_interface_property packetout2 SVD_ADDRESS_GROUP ""

add_interface_port packetout2 packetout_2_sop startofpacket Output 1
add_interface_port packetout2 packetout_2_eop endofpacket Output 1
add_interface_port packetout2 packetout_2_data data Output 64
add_interface_port packetout2 packetout_2_channel channel Output 6
add_interface_port packetout2 packetout_2_valid valid Output 1
add_interface_port packetout2 packetout_2_ready ready Input 1


# 
# connection point packetout3
# 
add_interface packetout3 avalon_streaming start
set_interface_property packetout3 associatedClock clock
set_interface_property packetout3 associatedReset reset
set_interface_property packetout3 dataBitsPerSymbol 8
set_interface_property packetout3 symbolsPerBeat 8
set_interface_property packetout3 errorDescriptor ""
set_interface_property packetout3 firstSymbolInHighOrderBits true
set_interface_property packetout3 maxChannel 63
set_interface_property packetout3 readyLatency 0
set_interface_property packetout3 ENABLED true
set_interface_property packetout3 EXPORT_OF ""
set_interface_property packetout3 PORT_NAME_MAP ""
set_interface_property packetout3 CMSIS_SVD_VARIABLES ""
set_interface_property packetout3 SVD_ADDRESS_GROUP ""

add_interface_port packetout3 packetout_3_sop startofpacket Output 1
add_interface_port packetout3 packetout_3_eop endofpacket Output 1
add_interface_port packetout3 packetout_3_data data Output 64
add_interface_port packetout3 packetout_3_channel channel Output 6
add_interface_port packetout3 packetout_3_valid valid Output 1
add_interface_port packetout3 packetout_3_ready ready Input 1


# 
# connection point tagin
# 
add_interface tagin avalon_streaming end
set_interface_property tagin associatedClock clock
set_interface_property tagin associatedReset reset
set_interface_property tagin dataBitsPerSymbol 10
set_interface_property tagin errorDescriptor ""
set_interface_property tagin firstSymbolInHighOrderBits false
set_interface_property tagin maxChannel 0
set_interface_property tagin readyLatency 0
set_interface_property tagin ENABLED true
set_interface_property tagin EXPORT_OF ""
set_interface_property tagin PORT_NAME_MAP ""
set_interface_property tagin CMSIS_SVD_VARIABLES ""
set_interface_property tagin SVD_ADDRESS_GROUP ""

add_interface_port tagin tagin_data data Input 10
add_interface_port tagin tagin_valid valid Input 1
add_interface_port tagin tagin_ready ready Output 1


# 
# connection point transmitout0
# 
add_interface transmitout0 avalon_streaming start
set_interface_property transmitout0 associatedClock clock
set_interface_property transmitout0 associatedReset reset
set_interface_property transmitout0 dataBitsPerSymbol 8
set_interface_property transmitout0 symbolsPerBeat 8
set_interface_property transmitout0 errorDescriptor ""
set_interface_property transmitout0 firstSymbolInHighOrderBits true
set_interface_property transmitout0 maxChannel 0
set_interface_property transmitout0 readyLatency 0
set_interface_property transmitout0 ENABLED true
set_interface_property transmitout0 EXPORT_OF ""
set_interface_property transmitout0 PORT_NAME_MAP ""
set_interface_property transmitout0 CMSIS_SVD_VARIABLES ""
set_interface_property transmitout0 SVD_ADDRESS_GROUP ""

add_interface_port transmitout0 transmitout_0_data data Output 64
add_interface_port transmitout0 transmitout_0_valid valid Output 1
add_interface_port transmitout0 transmitout_0_ready ready Input 1
add_interface_port transmitout0 transmitout_0_sop startofpacket Output 1
add_interface_port transmitout0 transmitout_0_eop endofpacket Output 1

# 
# connection point transmitout1
# 
add_interface transmitout1 avalon_streaming start
set_interface_property transmitout1 associatedClock clock
set_interface_property transmitout1 associatedReset reset
set_interface_property transmitout1 dataBitsPerSymbol 8
set_interface_property transmitout1 symbolsPerBeat 8
set_interface_property transmitout1 errorDescriptor ""
set_interface_property transmitout1 firstSymbolInHighOrderBits true
set_interface_property transmitout1 maxChannel 0
set_interface_property transmitout1 readyLatency 0
set_interface_property transmitout1 ENABLED true
set_interface_property transmitout1 EXPORT_OF ""
set_interface_property transmitout1 PORT_NAME_MAP ""
set_interface_property transmitout1 CMSIS_SVD_VARIABLES ""
set_interface_property transmitout1 SVD_ADDRESS_GROUP ""

add_interface_port transmitout1 transmitout_1_data data Output 64
add_interface_port transmitout1 transmitout_1_valid valid Output 1
add_interface_port transmitout1 transmitout_1_ready ready Input 1
add_interface_port transmitout1 transmitout_1_sop startofpacket Output 1
add_interface_port transmitout1 transmitout_1_eop endofpacket Output 1

# 
# connection point transmitout2
# 
add_interface transmitout2 avalon_streaming start
set_interface_property transmitout2 associatedClock clock
set_interface_property transmitout2 associatedReset reset
set_interface_property transmitout2 dataBitsPerSymbol 8
set_interface_property transmitout2 symbolsPerBeat 8
set_interface_property transmitout2 errorDescriptor ""
set_interface_property transmitout2 firstSymbolInHighOrderBits true
set_interface_property transmitout2 maxChannel 0
set_interface_property transmitout2 readyLatency 0
set_interface_property transmitout2 ENABLED true
set_interface_property transmitout2 EXPORT_OF ""
set_interface_property transmitout2 PORT_NAME_MAP ""
set_interface_property transmitout2 CMSIS_SVD_VARIABLES ""
set_interface_property transmitout2 SVD_ADDRESS_GROUP ""

add_interface_port transmitout2 transmitout_2_data data Output 64
add_interface_port transmitout2 transmitout_2_valid valid Output 1
add_interface_port transmitout2 transmitout_2_ready ready Input 1
add_interface_port transmitout2 transmitout_2_sop startofpacket Output 1
add_interface_port transmitout2 transmitout_2_eop endofpacket Output 1

# 
# connection point transmitout3
# 
add_interface transmitout3 avalon_streaming start
set_interface_property transmitout3 associatedClock clock
set_interface_property transmitout3 associatedReset reset
set_interface_property transmitout3 dataBitsPerSymbol 8
set_interface_property transmitout3 symbolsPerBeat 8
set_interface_property transmitout3 errorDescriptor ""
set_interface_property transmitout3 firstSymbolInHighOrderBits true
set_interface_property transmitout3 maxChannel 0
set_interface_property transmitout3 readyLatency 0
set_interface_property transmitout3 ENABLED true
set_interface_property transmitout3 EXPORT_OF ""
set_interface_property transmitout3 PORT_NAME_MAP ""
set_interface_property transmitout3 CMSIS_SVD_VARIABLES ""
set_interface_property transmitout3 SVD_ADDRESS_GROUP ""

add_interface_port transmitout3 transmitout_3_data data Output 64
add_interface_port transmitout3 transmitout_3_valid valid Output 1
add_interface_port transmitout3 transmitout_3_ready ready Input 1
add_interface_port transmitout3 transmitout_3_sop startofpacket Output 1
add_interface_port transmitout3 transmitout_3_eop endofpacket Output 1
